---
pipeline:
  projectIdentifier: "Test_1"
  orgIdentifier: "default"
  tags: {}
  stages:
  - stage:
      name: "P0"
      identifier: "P0"
      description: ""
      type: "Custom"
      spec:
        execution:
          steps:
          - step:
              type: "ShellScript"
              name: "ShellScript_1"
              identifier: "ShellScript_1"
              spec:
                shell: "Bash"
                executionTarget: {}
                source:
                  type: "Inline"
                  spec:
                    script: "echo \"Git Chain 0\"\necho \"<+pipeline.branch>\""
                environmentVariables: []
                outputVariables: []
              timeout: "10m"
      tags: {}
  identifier: "P0_Other"
  name: "P0 - Other"
