pipeline:
  name: p1
  identifier: p1
  projectIdentifier: Test_1
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: p1
        identifier: p1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: "2"
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo "<+pipeline.branch>"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
